"""LangGraph state definitions for all agent workflows."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field
from typing_extensions import TypedDict


# ==========================================================================
# Shared Types
# ==========================================================================


class Citation(BaseModel):
    """A citation from a data source."""

    source_type: str  # screener, pdf, news, web
    source_name: str
    url: str | None = None
    content_snippet: str | None = None
    page_number: int | None = None


class ToolResult(BaseModel):
    """Result from a tool execution."""

    tool_name: str
    output: dict[str, Any]
    citations: list[Citation] = Field(default_factory=list)
    execution_time_ms: int = 0


class ThoughtStep(BaseModel):
    """A single reasoning step in the agent workflow."""

    step_type: str  # planning, researching, analyzing, reflecting, reporting
    title: str
    content: str = ""
    confidence: float | None = None


class ResearchPlan(BaseModel):
    """A plan generated by the Planner node."""

    tasks: list[str]
    tools_needed: list[str]
    rationale: str


# ==========================================================================
# Deep Research State
# ==========================================================================


class ResearchState(TypedDict, total=False):
    """State for the Deep Research agent graph."""

    # Input
    query: str
    ticker: str | None

    # Execution
    messages: list[dict[str, Any]]
    plan: ResearchPlan | None
    current_step: int
    thought_log: list[ThoughtStep]

    # Data
    tool_results: list[ToolResult]
    citations: list[Citation]

    # Analysis
    analysis_draft: str
    critic_feedback: str
    iteration_count: int

    # Output
    final_report: str
    executive_summary: str

    # Control
    status: str  # planning | researching | analyzing | reflecting | reporting | complete | error
    should_continue: bool
    session_id: str


# ==========================================================================
# Macro Analyzer State
# ==========================================================================


class ParsedEvent(BaseModel):
    """Parsed geopolitical / economic event."""

    event_type: str
    actors: list[str]
    action: str
    primary_commodity: str | None = None
    price_direction: str | None = None  # bullish, bearish, neutral
    affected_regions: list[str] = Field(default_factory=list)


class CausalLink(BaseModel):
    """A single link in a causal chain."""

    from_event: str
    to_event: str
    relationship: str
    confidence: float
    evidence: str | None = None


class CompanyExposure(BaseModel):
    """A company's exposure to a macro event."""

    ticker: str
    company_name: str
    exposure_type: str
    impact_direction: str  # positive, negative, neutral
    impact_magnitude: str  # strong, moderate, mild
    current_metrics: dict[str, Any] = Field(default_factory=dict)
    projected_impact: str = ""
    confidence: float = 0.0
    historical_precedent: str | None = None


class TradeIdea(BaseModel):
    """A trade recommendation."""

    action: str  # LONG or SHORT
    ticker: str
    entry_price: float | None = None
    target_price: float | None = None
    stop_loss: float | None = None
    conviction: str  # high, medium, low
    rationale: str = ""


class MacroAnalyzerState(TypedDict, total=False):
    """State for the Macro Analyzer agent graph."""

    # Input
    query: str

    # Event parsing
    parsed_event: ParsedEvent | None
    affected_regions: list[str]

    # Research
    web_research_results: list[dict[str, Any]]
    news_context: list[dict[str, Any]]

    # Reasoning
    causal_chain: list[CausalLink]
    reasoning_steps: list[str]

    # Company analysis
    affected_companies: list[CompanyExposure]
    trade_ideas: list[TradeIdea]

    # Output
    executive_summary: str
    full_report: str

    # Tracking
    thought_log: list[ThoughtStep]
    citations: list[Citation]
    status: str
    iteration_count: int
    session_id: str
